### ISSUE TITLE
build CodeTransform::core

### ISSUE THREAD

**Issue by monperrus** [thanhlecongg/NaturalTransformationForBenchmarkingNPR#1]
Thanks for the repo!

I'd like to build [core](https://github.com/thanhlecongg/NaturalTransformationForBenchmarkingNPR/tree/main/tools/CodeTransform/core). However, there is no build file (such as pom.xml or build.gradle).

How to build core?

Thanks!

**Comment by thanhlecongg** [comment]
Hi, thank you for your interest. Please follow the instructions in this [README](https://github.com/thanhlecongg/NaturalTransformationForBenchmarkingNPR/tree/main/tools/CodeTransform#readme). I have used IntelliJ IDE and built directly using their dependencies management.

**Comment by monperrus** [comment]
In the instructions, there is no Jar files to download as dependencies.

Thanks.

**Comment by thanhlecongg** [comment]
Ah, I see. It is my mistake. Sorry about that. I will upload it after I wake up (as now is 4 a.m. in my time zone) and let you know when it is completed.

**Comment by monperrus** [comment]
great, thanks.

FYI: a pom.xml is easier and more reliable than IDE building for other researchers.

**Comment by thanhlecongg** [comment]
Hi @monperrus,

I have updated our Figshare repo to include dependencies of CodeTransform. For your convenience, please see this [link](https://figshare.com/s/05c50e7e0bd021ed16b3).

Regarding pom.xml, I agree with your point. When implementing this tool, I have re-used these dependencies from SPAT so I have not created pom.xml. I will refactor the code following Maven once my schedule allows it. Please kindly let me know if you have any further questions.

**Comment by monperrus** [comment]
thanks a lot @thanhlecongg 

also it would be great to have a `requirements.txt` in [CodeTransform](https://github.com/thanhlecongg/NaturalTransformationForBenchmarkingNPR/tree/main/tools/CodeTransform) to get the Python dependencies right.

**Comment by thanhlecongg** [comment]
Hi @monperrus,

I have updated [enviroment](https://github.com/thanhlecongg/NaturalTransformationForBenchmarkingNPR/blob/main/tools/CodeTransform/enviroment.yml) to the repo. Please use `conda` for installation. Hope it help.

**Comment by monperrus** [comment]
thanks!

**Comment by thanhlecongg** [comment]
As this issue is done, I will close it. Feel free to open it again if there are any problems. Thanks.

**Comment by thanhlecongg** [comment]
@monperrus, I have released my code transformation tool as independent repository, which now uses Maven for dependency management and features an improved workflow. If you are interested in this tool, you may want to check this [repo](https://github.com/thanhlecongg/NaturalCodeTransformer).

**Comment by monperrus** [comment]
Thanks a lot @thanhlecongg , I confirm I can build it with Maven.
